import { Cirurgia, Paciente, TermoConsentimento } from '@operus/types';

export const mockSurgeon = {
  id: 'usr-med-01',
  nome: 'Dr. Roberto Silveira',
  crm: 'CRM/SP 142.890',
  especialidade: 'Cirurgia Geral & Videolaparoscopia',
  clinica: 'Operus Surgical Group - SP',
  email: 'roberto.silveira@operus.med.br',
  foto: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
};

export const mockPacientes: Paciente[] = [
  {
    id: 'pac-01',
    user_id: 'usr-med-01',
    nome: 'Mariana Duarte Costa',
    cpf: '341.***.***-09',
    rg: '44.890.112-X',
    data_nascimento: '1988-04-12',
    sexo: 'F',
    telefone: '(11) 98765-4321',
    email: 'mariana.costa@email.com',
    cep: '01310-100',
    endereco: 'Av. Paulista',
    numero: '1200',
    complemento: 'Apto 42',
    bairro: 'Bela Vista',
    cidade: 'São Paulo',
    estado: 'SP',
    convenio_id: 'conv-bradesco',
    numero_carteirinha: '8901234455-0',
    observacoes_medicas: 'Alergia a Dipirona e Frutos do Mar. Sem histórico de TVP.',
    contato_emergencia_nome: 'Carlos Costa (Esposo)',
    contato_emergencia_telefone: '(11) 98111-2233',
  },
  {
    id: 'pac-02',
    user_id: 'usr-med-01',
    nome: 'Eduardo Martins Fontes',
    cpf: '219.***.***-45',
    rg: '38.120.941-5',
    data_nascimento: '1976-11-28',
    sexo: 'M',
    telefone: '(11) 99123-8877',
    email: 'eduardo.fontes@email.com',
    cep: '04538-132',
    endereco: 'Rua Joaquim Floriano',
    numero: '450',
    complemento: 'Conj 81',
    bairro: 'Itaim Bibi',
    cidade: 'São Paulo',
    estado: 'SP',
    convenio_id: 'conv-sulamerica',
    numero_carteirinha: '4409182377-1',
    observacoes_medicas: 'Hipertenso controlado com Losartana 50mg.',
    contato_emergencia_nome: 'Patrícia Fontes',
    contato_emergencia_telefone: '(11) 99222-3344',
  },
  {
    id: 'pac-03',
    user_id: 'usr-med-01',
    nome: 'Camila Albuquerque Maia',
    cpf: '402.***.***-81',
    rg: '50.334.812-3',
    data_nascimento: '1995-07-03',
    sexo: 'F',
    telefone: '(11) 97654-1122',
    email: 'camila.maia@email.com',
    cep: '05422-000',
    endereco: 'Rua dos Pinheiros',
    numero: '890',
    complemento: null,
    bairro: 'Pinheiros',
    cidade: 'São Paulo',
    estado: 'SP',
    convenio_id: 'conv-unimed',
    numero_carteirinha: '1092837465-9',
    observacoes_medicas: 'Nega comorbidades ou cirurgias prévias.',
    contato_emergencia_nome: 'Ana Maia (Mãe)',
    contato_emergencia_telefone: '(11) 97111-9988',
  }
];

export const mockCirurgias: Cirurgia[] = [
  {
    id: 'cir-001',
    user_id: 'usr-med-01',
    paciente_id: 'pac-01',
    convenio_id: 'conv-bradesco',
    hospital_nome: 'Hospital Sírio-Libanês',
    sala_cirurgica: 'Centro Cirúrgico 04 (Torre B)',
    data_cirurgia: '2026-10-02T07:30:00Z',
    duracao_estimada_minutos: 90,
    status: 'autorizada',
    tipo_anestesia: 'Geral balanceada + Bloqueio TAP',
    necessita_opme: true,
    opme_descricao: 'Kit Trocarte Óptico 5mm/10mm + Clipe de Titânio Laparoscópico LT300 (Johnson & Johnson)',
    status_opme: 'Entregue e Conferido',
    observacoes: 'Paciente em jejum desde 22h. TCLE assinado digitalmente com carimbo SHA-256.',
    paciente: mockPacientes[0],
    procedimentos: [
      {
        id: 'proc-01',
        cirurgia_id: 'cir-001',
        codigo_tuss: '31005452',
        descricao: 'Colecistectomia por videolaparoscopia com colangiografia',
        via_acesso: 'mesma_via',
        percentual_pagamento: 100,
        valor_estimado: 4850.00,
      }
    ],
    equipe: [
      {
        id: 'eq-01',
        cirurgia_id: 'cir-001',
        membro_nome: 'Dr. Roberto Silveira',
        funcao: 'cirurgiao_principal',
        crm: 'CRM/SP 142.890',
        valor_honorario: 3500.00,
        status_repasse: 'pendente',
      },
      {
        id: 'eq-02',
        cirurgia_id: 'cir-001',
        membro_nome: 'Dra. Letícia Carvalho',
        funcao: 'primeiro_auxiliar',
        crm: 'CRM/SP 178.432',
        valor_honorario: 1050.00,
        status_repasse: 'pendente',
      },
      {
        id: 'eq-03',
        cirurgia_id: 'cir-001',
        membro_nome: 'Dr. Fernando Prado (Anestesista)',
        funcao: 'anestesista',
        crm: 'CRM/SP 119.554',
        valor_honorario: 1400.00,
        status_repasse: 'pendente',
      }
    ]
  },
  {
    id: 'cir-002',
    user_id: 'usr-med-01',
    paciente_id: 'pac-02',
    convenio_id: 'conv-sulamerica',
    hospital_nome: 'Hospital Albert Einstein',
    sala_cirurgica: 'Sala Cirúrgica Robótica 02',
    data_cirurgia: '2026-10-02T11:00:00Z',
    duracao_estimada_minutos: 120,
    status: 'autorizada',
    tipo_anestesia: 'Raquianestesia com sedação',
    necessita_opme: true,
    opme_descricao: 'Tela de Polipropileno 3D 10x15cm + Grampeador Laparoscópico Articulado',
    status_opme: 'Pendente Entrega (Fornecedor B.Braun)',
    observacoes: 'Herniorrafia Inguinal Bilateral via TAPP.',
    paciente: mockPacientes[1],
    procedimentos: [
      {
        id: 'proc-02',
        cirurgia_id: 'cir-002',
        codigo_tuss: '31005231',
        descricao: 'Herniorrafia inguinal bilateral por videolaparoscopia',
        via_acesso: 'bilateral',
        percentual_pagamento: 100,
        valor_estimado: 5600.00,
      }
    ],
    equipe: [
      {
        id: 'eq-04',
        cirurgia_id: 'cir-002',
        membro_nome: 'Dr. Roberto Silveira',
        funcao: 'cirurgiao_principal',
        crm: 'CRM/SP 142.890',
        valor_honorario: 4200.00,
        status_repasse: 'pendente',
      }
    ]
  },
  {
    id: 'cir-003',
    user_id: 'usr-med-01',
    paciente_id: 'pac-03',
    convenio_id: 'conv-unimed',
    hospital_nome: 'Hospital Nove de Julho',
    sala_cirurgica: 'Sala Cirúrgica 08',
    data_cirurgia: '2026-10-03T08:00:00Z',
    duracao_estimada_minutos: 60,
    status: 'em_autorizacao',
    tipo_anestesia: 'Geral',
    necessita_opme: false,
    opme_descricao: null,
    status_opme: 'Sem OPME',
    observacoes: 'Aguardando auditoria prévia do convênio Unimed.',
    paciente: mockPacientes[2],
    procedimentos: [
      {
        id: 'proc-03',
        cirurgia_id: 'cir-003',
        codigo_tuss: '31005010',
        descricao: 'Apendicectomia por videolaparoscopia',
        via_acesso: 'mesma_via',
        percentual_pagamento: 100,
        valor_estimado: 3900.00,
      }
    ]
  }
];

export const mockTermos: TermoConsentimento[] = [
  {
    id: 'tcle-001',
    user_id: 'usr-med-01',
    paciente_id: 'pac-01',
    cirurgia_id: 'cir-001',
    titulo: 'TCLE - Colecistectomia Videolaparoscópica',
    corpo_termo: 'Declaro que fui amplamente informado(a) pelo Dr. Roberto Silveira sobre os objetivos, benefícios, riscos potenciais e alternativas cirúrgicas ao procedimento proposto...',
    riscos_especificos: [
      'Sangramento intraoperatório ou hematoma',
      'Infecção de sítio cirúrgico ou cavidade',
      'Lesão iatrogênica de vias biliares ou duodeno',
      'Conversão para cirurgia aberta (laparotomia) se indicado',
    ],
    beneficios_esperados: [
      'Alívio definitivo de crises de cólica biliar',
      'Prevenção de complicações como coledocolitíase e pancreatite aguda',
      'Recuperação acelerada e menor dor pós-operatória',
    ],
    token_aceite: 'tcle-sha256-mariana-duarte-20261001-a9f8b4',
    status_aceite: 'aceito',
    data_aceite: '2026-10-01T14:22:15Z',
    ip_aceite: '177.132.89.44',
    user_agent_aceite: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15',
    geolocalizacao_aceite: { lat: -23.5617, lng: -46.6559, accuracy_m: 12 },
    assinatura_digital_url: 'data:image/svg+xml;utf8,<svg ... />',
    paciente: mockPacientes[0],
    cirurgia: mockCirurgias[0],
  },
  {
    id: 'tcle-002',
    user_id: 'usr-med-01',
    paciente_id: 'pac-02',
    cirurgia_id: 'cir-002',
    titulo: 'TCLE - Herniorrafia Inguinal Laparoscópica TAPP',
    corpo_termo: 'Declaro para os devidos fins legais em conformidade com a Resolução CFM 2.299/2021 que recebi as orientações e concordo com o implante de tela cirúrgica de reforço...',
    riscos_especificos: [
      'Dor crônica neuropática ou parestesia transitória',
      'Seroma ou equimose escrotal/inguinal',
      'Recidiva herniária tardia (<2%)',
    ],
    beneficios_esperados: [
      'Correção anatômica do defeito da parede abdominal',
      'Retorno precoce às atividades laborais e esportivas',
    ],
    token_aceite: 'tcle-sha256-eduardo-fontes-20261001-c8e17b',
    status_aceite: 'pendente',
    data_aceite: null,
    ip_aceite: null,
    user_agent_aceite: null,
    geolocalizacao_aceite: null,
    assinatura_digital_url: null,
    paciente: mockPacientes[1],
    cirurgia: mockCirurgias[1],
  }
];
